name: RabbitMQ
services:
  rabbitmq:
    build:
      context: .
      args:
        LDAP_SERVER: 130.88.41.197
        LDAP_PORT: 3890
        LDAP_SSL: false
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "1883:1883"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host
volumes:
  rabbitmq_data:
    name: rabbitmq-data
