name: RabbitMQ
services:
  rabbitmq:
    build:
      context: .
      args:
        LDAP_SERVER: apperture-ldap
        LDAP_PORT: 3890
        LDAP_SSL: false
    container_name: rabbitmq
    ports:
      - "1883:1883"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mqtt
networks:
  mqtt:
    name: apperture_apperture
    external: true
volumes:
  rabbitmq_data:
    name: rabbitmq-data
